# Generated by Django 5.2.9 on 2026-01-07 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doccare',
            old_name='department',
            new_name='name',
        ),
    ]
