# Generated by Django 5.2.9 on 2026-01-07 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_rename_department_doccare_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocCare',
            new_name='Department',
        ),
    ]
