# Generated by Django 5.2.9 on 2026-01-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_rename_doccare_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
